# Generated by Django 5.0.3 on 2024-03-26 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triviabyte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
