# Generated by Django 5.0.3 on 2024-03-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triviabyte', '0002_rename_answers_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='marks',
            field=models.IntegerField(default=1),
        ),
    ]
